#!/bin/sh

WERCKER_DOCKER_SWARM_USER=${WERCKER_DOCKER_SWARM_USER:-root}
WERCKER_DOCKER_SWARM_SERVICE=${WERCKER_DOCKER_SWARM_SERVICE:-$WERCKER_GIT_REPOSITORY}

cat cmd.sh | ssh -o PasswordAuthentication=no "$WERCKER_DOCKER_SWARM_USER@$WERCKER_DOCKER_SWARM_MANAGER" "\
    WERCKER_DOCKER_SWARM_SERVICE=$WERCKER_DOCKER_SWARM_SERVICE \
    WERCKER_DOCKER_SWARM_IMAGE=$WERCKER_DOCKER_SWARM_IMAGE \
    WERCKER_DOCKER_SWARM_TAG=$WERCKER_DOCKER_SWARM_TAG \
    bash -s"
