#!/bin/sh

WERCKER_DOCKER_SWARM_USER=${WERCKER_DOCKER_SWARM_USER:-root}
WERCKER_DOCKER_SWARM_SERVICE=${WERCKER_DOCKER_SWARM_SERVICE:-$WERCKER_GIT_REPOSITORY}

ssh "$WERCKER_DOCKER_SWARM_USER@$WERCKER_DOCKER_SWARM_MANAGER" "docker service ps $WERCKER_DOCKER_SWARM_SERVICE \
&& docker service update --detach=false --update-order=start-first --with-registry-auth --image $WERCKER_DOCKER_SWARM_IMAGE:$WERCKER_DOCKER_SWARM_TAG $WERCKER_DOCKER_SWARM_SERVICE \
|| echo docker service create --detach=false --name $WERCKER_DOCKER_SWARM_SERVICE --with-registry-auth $WERCKER_DOCKER_SWARM_IMAGE:$WERCKER_DOCKER_SWARM_TAG"
